### ISSUE TITLE
dissapointed.

### ISSUE THREAD

**Issue by DiamondMiner88** [hubble459/nhentai.js#1]
man if you're gonna just clone my project at least make the README different.
its fucking identical

**Comment by hubble459** [comment]
Its only the readme that's basically the same 😳 and I'm sorry for that. I will change it right away.

I'm not sure what you mean by 'clone', but all code was written by me.. :c

I hope you'll understand and not be angy 🥺

**Comment by DiamondMiner88** [comment]
yeah I did see you had diff code

anyway thanks
i was a bit too aggressive lmao, sorry
